### ISSUE TITLE
Multi language support does not work

### ISSUE THREAD

**Issue by venuswu** [Yelp/yelp-fusion#101]
Code as follows:
```
import io
import json
from yelp.client import Client
from yelp.oauth1_authenticator import Oauth1Authenticator


with io.open('config_secret.json') as cred:
    creds = json.load(cred)
    auth = Oauth1Authenticator(**creds)
    client = Client(auth)

    params = {
          'lang' : 'cn'
    }

    response = client.get_business('yelp-san-francisco', **params)
    print response.business.name
    print response.business.categories
```
Only results in English are shown no matter what lang is set. 
Please check~~.

**Comment by mittonk** [comment]
@venuswu : 
(Looks like you're using API V2 https://github.com/Yelp/yelp-api rather than Fusion, so I'll answer in those terms.  It also looks like you're using the Python clientlib for V2, https://github.com/yelp/yelp-python .)

1. `lang` expects an ISO-639 language code:
* https://www.yelp.com/developers/documentation/v2/business
* https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

I have a hunch you're looking for Chinese reviews --- try language code `zh`, not `cn`.

There aren't a ton of Chinese reviews in San Francisco (this business only has 1); you'll get more matches in Hong Kong or Taiwan.  You can also try `fr` or `de` for French or German, just to make sure things work.

2. For Fusion users who find this thread: the equivalent Fusion `locale` parameter takes these supported locales:
* https://www.yelp.com/developers/documentation/v3/supported_locales
