### ISSUE TITLE
Reviews API returns user's profile photo in full resolution 

### ISSUE THREAD

**Issue by razola** [Yelp/yelp-fusion#115]
Hi, 

Version 2 of the API returned a small square thumbnail image while V3 now returns a full resolution image. For example:

v2 -> https://s3-media2.fl.yelpcdn.com/bphoto/kdLPw2Jhr4axSH6OQD0oKQ/o.jpg
v3 -> https://s3-media2.fl.yelpcdn.com/bphoto/kdLPw2Jhr4axSH6OQD0oKQ/ms.jpg

Is this the intentional?

If not, a workaround that seems to work is to simply change the filename from o.jpg to ms.jpg. Is this a solution that will work in the future?

Thanks!

**Comment by tomelm** [comment]
This is an intentional change on our side. We wanted to provide people with the hi-res images so that displaying content on high resolution displays looked nice and not blurry. Renaming o.jpg to ms.jpg will work but I can't promise that the file structure won't change in the future so I'd advise against using it.

**Comment by razola** [comment]
Ok, thanks for the quick reply!
