### ISSUE TITLE
Discrepancies in Search results

### ISSUE THREAD

**Issue by akkrisan** [Yelp/yelp-fusion#144]
The Search API isn't giving me any results whereas using the same parameters in the normal yelp search produces results.

Here's one specific example I was looking at:
Results from the Yelp site-
https://www.yelp.com/search?find_desc=BlueLine+Rental&find_loc=Mabelvale%2C+AR&ns=1

Plug the same parameters into the Yelp api console-
https://www.yelp.com/developers/api_console
using parameters:
_find_- BlueLine+Rental
_near_- Mabelvale+AR
_radius_- 40000

I get the same results from the api call in my app as I do from the api console. No businesses.
Am I doing something wrong here?

**Comment by mittonk** [comment]
@akkrisan : Looks like you're using the older V2 API supported over at https://github.com/Yelp/yelp-api rather than Yelp Fusion, but the answer here would be the same in either version:

Businesses with 0 reviews aren't returned by Yelp Fusion:
* https://www.yelp.com/developers/documentation/v3/business_search
> Note: at this time, the API does not return businesses without any reviews.
* (older V2 version: https://www.yelp.com/developers/documentation/v2/search_api )

Sorry!
