### ISSUE TITLE
Search API returns irrelevant results?

### ISSUE THREAD

**Issue by razola** [Yelp/yelp-fusion#195]
In the example request below I search for the term "pizza" and filter results to only show businesses from the "restaurants" category. As you can see the first four results has nothing to do with pizza. I know that I can filter on the category "pizza", but sometimes businesses aren't tagged with every category of food they serve..

### Request
https://api.yelp.com/v3/businesses/search?term=pizza&categories=restaurants&radius=1000&latitude=38.452689607773834&longitude=-122.75137692518068&sort_by=rating

### Results
**los-arcos-santa-rosa**
4.5 (299)
Mexican, American (Traditional)

**go-go-wok-santa-rosa**
3.5 (83)
Chinese

**remys-bar-and-grill-santa-rosa-3**
3.5 (69)
Lounges, American (New)

**china-star-santa-rosa**
3.5 (71)
Chinese

**round-table-pizza-santa-rosa-5**
3.0 (33)
Pizza

**papa-murphys-santa-rosa**
3.0 (14)
Pizza

**pizza-hut-santa-rosa-2**
2.5 (28)
Pizza, Italian, Chicken Wings

**Comment by tomelm** [comment]
Search uses many different signals to find businesses when you search by term, and a lot of the less relevant ones tend to get filtered out when you filter by best_match. Since you're sorting by rating, a lot of different factors could cause these to pop up over normally better options. Category filtering is probably the best bet here or going back to regular best_match sort

**Comment by razola** [comment]
Got it. Thanks for the quick reply!
