### ISSUE TITLE
Locale changing does not work.

### ISSUE THREAD

**Issue by Dainius-P** [Yelp/yelp-fusion#198]
Hello, I would like to get the businesses information from the Italian yelp website. It that is possible? Changing the locale does not work.

**Comment by mittonk** [comment]
@Dainius-P : What endpoint are you looking at (full URL), and how is the result different from what you expect?

Search seem seem to work for me:
* https://api.yelp.com/v3/businesses/search?location=roma&term=vino&locale=it_IT
```
{
  "businesses": [
    {
      "id": "sorpasso-roma",
      "name": "Sorpasso",
      "review_count": 52,
...
```

Business seems to work for me:
* https://api.yelp.com/v3/businesses/sorpasso-roma?locale=it_IT
```
{
  "id": "sorpasso-roma",
  "name": "Sorpasso",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/gLj3jcX6HC4XfCOYq8OP7Q/o.jpg",
  "location": {
    "country": "IT",
    "address1": "Via Properzio 31",
    "state": "RM",
    "address2": "",
    "city": "Roma",
    "address3": "",
    "zip_code": "00193",
    "cross_streets": "",
    "display_address": [
      "Via Properzio 31",
      "00193 Roma"
    ]
  },
...
```

**Comment by Dainius-P** [comment]
I need to find businesses in Italy by by category:
`params = {'location': 'Ancona', 
'categories': 'food',
'locale': 'it_IT'
}`
And it only retrieves 44 results. Also another question. Can I use Italian categories like: Gastronomia, Animali domestici etc.

**Comment by mittonk** [comment]
OK, I also see 44 results in https://api.yelp.com/v3/businesses/search?categories=food&location=ancona&locale=it_IT .  So, reproduced issue.

The Yelp API only returns businesses with reviews --- so we need businesses in Ancona, in category "food", with a review in your requested language of Italian.

Is there an example business you expect to see that isn't showing up?  Having a concrete example would help.

Regarding categories: please use the category aliases listed on https://www.yelp.com/developers/documentation/v3/all_category_list , rather than the English or Italian display titles.

**Comment by Dainius-P** [comment]
Okay then another example. I need to get all of the 6469 businesses from https://www.yelp.it/search?find_desc=&find_loc=Ancona&ns=1 . The code I mentioned earlier without using a specific category, brings back only ~250 bussineses.

**Comment by mittonk** [comment]
@Dainius-P : Hm, this still sounds like the "must have a review" condition.  Could you provide a Yelp link or ID for a business that you think you should be able to get in a search, but can't?

**Comment by smflanag** [comment]
This still doesn't seem to be working: https://api.yelp.com/v3/businesses/search?location=Grafton+Street&term=pub&radius=1000&limit=20&locale=en_IE
The above defaults to returning results from MA, USA, even with locale for Ireland selected.
