### ISSUE TITLE
GraphQL query limit?

### ISSUE THREAD

**Issue by razola** [Yelp/yelp-fusion#224]
[The docs say](https://www.yelp.com/developers/graphql/guides/intro): 

> If you use multiple queries in a single request, we will count each individual query called, so 3 uses of the business queries will in a single request will count 3 off your total.

Does this mean that a search like the below will count as 5 requests?

`{
    search(term: "burrito",
            location: "san francisco",
            limit: 5) {
        total
        business {
            name
            url
        }
    }
}
`

**Comment by tomelm** [comment]
Nope! That's only 1. It's every call into one of the top level queries that counts against the limit (it's the 4 that are listed under "Query" on the left-nav: https://www.yelp.com/developers/graphql/query/search)

The business you're requesting there is just an [object](https://www.yelp.com/developers/graphql/objects/business) so that doesn't count against you.

**Comment by razola** [comment]
Great! Thank you!
