### ISSUE TITLE
image_url and price missing from GraphQL

### ISSUE THREAD

**Issue by Pinski** [Yelp/yelp-fusion#226]
So I'm using the GraphQL (so far it's exactly what I was looking for) and I noticed a couple of fields are missing.  According to your [Business documentation](https://www.yelp.com/developers/graphql/query/business), GraphQL is supposed to support image_url.  However, when I used it, I get the following error:
`{
  "data": null,
  "errors": [
    "Cannot query field \"image_url\" on type \"Business\"."
  ]
}`

Also, I know price isn't listed in your documentation as being supported by GraphQL, but this is the only field missing that I would want to use.  I imagine it's a popular field and the fact that it is missing is just a mistake.  Or it's more complicated to retrieve than I imagine and it was left out on purpose.

Thanks again.

**Comment by tomelm** [comment]
Price missing is an oversight on our part, I'll look into adding that.

image_url is in fact not available. We removed it since it's redundant with the photos field. The first photo of the photos field and image_url are always the same so you can use photos inside. I'll update the documentation to remove the image_url mention.

**Comment by Pinski** [comment]
Great, thanks for the follow up.

**Comment by tomelm** [comment]
Price should be live and I've removed image_url from the docs.
