### ISSUE TITLE
Finding "CLOSED" Businesses

### ISSUE THREAD

**Issue by ccoplai** [Yelp/yelp-fusion#249]
I'm attempting to run an analysis of companies that have gone out of business. Is there a way to utilize the Yelp Fusion API to filter and return only businesses in a certain geography for which the "is_closed" value is TRUE? 

I'm having trouble determining the best way to go about gathering this information, though I know it **should** be possible. Happy to provide additional detail as necessary.

**Comment by tomelm** [comment]
Unfortunately, there's not an easy way to do that on the API. Finding closed businesses isn't generally something people explicitly search for so it's not something we've surfaced.

**Comment by deepnadevkar** [comment]
I'm trying to do the exact same thing too! @ccoplai have you figured out a workaround?

Thanks!

**Comment by ccoplai** [comment]
Hi @deepnadevkar -- I have not found a workaround yet besides simply trying to gather as many companies as possible in a given area and filter to find those that are closed. Would be much easier if there were a way to simply find the closed ones in one search. You can also google "Yelp CLOSED [location]" and get some that are closed, but it definitely doesn't seem to be all inclusive...

**Comment by deepnadevkar** [comment]
@ccoplai Right, you could also use the Search API to identify all of the businesses in a specified geolocation, save them in a list and then use the Business API to return booleans using the "is_closed" parameter. The rest can be handled in python. I might try that strategy. 

Thanks for the response!

**Comment by AnnaDanielle** [comment]
I was trying to do this months ago too! It proves to be very hard because Yelp assumes you're not searching for closed businesses, so it's difficult to get the closed businesses more towards to top of the "best results" search...

**Comment by dgodevais** [comment]
Also attempting this with no success. I've returned over 1000 results for one zip code and none of the businesses are marked as permanently closed :/

**Comment by quytennis** [comment]
Searching for closed businesses isn't a typical use case for developers who want to use the Yelp API to show open businesses to users. What is your use case in looking for ONLY closed businesses?

**Comment by dgodevais** [comment]
@quytennis it's for a research project. Regardless, I'm not sure what the harm would be in allowing folks to filter across an arbitrary field unless the data is sensitive.

**Comment by sulphide0** [comment]
obviously knowing if a business is closed is considered useful, otherwise yelp wouldn't record this information in the first place. so it shouldn't be hard to imagine use cases (if you have content with business references, you clearly have many use cases for this).

**Comment by revwines** [comment]
Yes, we are doing research on closed restaurants near us.  Would be extremely useful

**Comment by jessebikman** [comment]
I am interested in this feature as well. Sometimes I want to remember the name of a place in a location that I used to visit, and the reviews or metadata can often give hints as to what happened with the business, who owned it, why it closed, and where things wound up with the business. Helps give the context of a space, particularly in lower population environments.

**Comment by alvarobartt** [comment]
I am also highly interested in this feature since search just for closed business can provide a lot of useful data for analysis. 

Maybe default `businesses/search` endpoint remains the same, but including an optional parameter than can let the users to search just for open/closed business such as `is_open` which is a boolean with True and False values, respectively. 

Thank you for you attention! Keep on the great work you are doing @ Yelp!

**Comment by Mikhail-MM** [comment]
This should be an exposed feature and it's important for historical purposes as well.

**Comment by hcheadle** [comment]
A few months have passed since the last comment on this topic. Has anyone found a way to successfully do this on Yelp or Google Maps (or other means)? Thank you in advance!!

**Comment by mcmay** [comment]
I do not particularly intend to track closed businesses, but it would be helpful to know the permanently closed businesses so as not to show them to the users of my app. It would be embarrassing or discrediting if a business was permanently closed and the users tried to contact that business or even travel to the location of the business only to find it closed down already or not there at all. YELP API should be responsible to expose such information if it is in their possession since it puts a `closed` boolean variable in the `Business` class.
