### ISSUE TITLE
Passing in google places business names to yelp autocomplete endpoint issues

### ISSUE THREAD

**Issue by JasonMannon** [Yelp/yelp-fusion#255]
I'm trying to pass in google places business names to the yelp autocomplete endpoint, but having some issues getting the correct results from yelp.  For some businesses Google adds additions to business names.  For example: 'Iris Tattoo' in Miami, FL turns into 'Iris Tattoo LLC'.  Yelp doesn't recognize 'Iris Tattoo LLC' but does recognize 'Iris Tattoo'.  Does anyone have a possible work around so Yelp can return business data for 'Iris Tattoo' when passing in 'Iris Tattoo LLC'?

**Comment by mittonk** [comment]
1. Different databases (Yelp, Google, etc) have different standards on how to format business names --- one approach would be to have your code strip of "LLC", "Inc.", "Ltd." and other legalese.  

There are a lot of edge cases and exceptions --- but I suspect you could build a heuristic that handles most of the usual cases pretty quickly.

Matching businesses between two databases is always a bit fiddly if there's not a published mapping of `yelp_business_id` to `google_business_id`, and there isn't one here.

2. From your description (finding specific Yelp businesses based on already-known names and addresses), you might also want to try our new Business Match endpoint:
* https://www.yelp.com/developers/documentation/v3/business_match

It requires much more prior knowledge about the business than Autocomplete (full name and address, rather than just part of the name and a vague location), but might be a good match for your use case.

Does that give you something to work with?

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
