### ISSUE TITLE
BUSINESS_UNAVAILABLE response returned in a different way. It is not a validation error anymore

### ISSUE THREAD

**Issue by bizmate** [Yelp/yelp-fusion#257]
This is a new variation of the issue #66 .
@mittonk as you can see here the response is slightly different. 

request

>  https://api.yelp.com/v3/businesses/bar-trattoria-san-pietro-san-pietro/reviews

response
```
{
    "error": {
        "code": "BUSINESS_UNAVAILABLE",
        "description": "We may not be able to provide details for certain businesses, for example if they do not have any reviews yet."
    }
}
```

The problem is the same. Could you please confirm this is the issue? As the response is not the same.
 
In a use case where a platform does not have end user locale information then there is no good way to fetch reviews as default is only for en_US. 
Also any chance #136 is going to be implemented any soon? I am stuck without it and querying the api for all locales feels really bad as a workaround

**Comment by bizmate** [comment]
Also a quick note, If I open https://www.yelp.com/biz/bar-trattoria-san-pietro-san-pietro with my browser sending `accept-language:en-GB,en;q=0.8,en-US;q=0.6,it;q=0.4` I still see the italian review. It is definitely not consistent with the API

**Comment by mittonk** [comment]
@bizmate : We've just changed some edge cases here, see
* https://www.yelp.com/developers/v3/changelog#changelog-20170705

`https://api.yelp.com/v3/businesses/bar-trattoria-san-pietro-san-pietro/reviews`
(which is equivalent to `https://api.yelp.com/v3/businesses/bar-trattoria-san-pietro-san-pietro/reviews?locale=en_US`)
now shows:
```
{
    "reviews": [],
    "total": 1
}
```
The one review is in Italian, so doesn't match the default `en_US` locale --- but we're now returning a clearer HTTP 200 OK and an empty array.  Does that help?

The web interface does have many more pieces of data (such as both business info and a search bar), and many more layers of fallback than Fusion API --- that's intentional.

**Comment by bizmate** [comment]
@mittonk thank you very much for getting back to me. I am aware about the default locale. Also I actually think a 404 is more appropiate if an actual resource is not returned but this is just semantics. I would say if there was a way to know available locales that would be a possible workaround as clients can become aware of how to query for the correct language.
Or even better if #136 is done then it would be the best also to minimise amount of http calls. At the moment I have also implemented a fall back to V2 and it feels ugly

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

(To get reviews in different languages use the `locale` param, the default value is `en_US`)
