### ISSUE TITLE
Search for businesses returns some coordinates with null latitude and longitude. 

### ISSUE THREAD

**Issue by zuchie** [Yelp/yelp-fusion#266]
It looks like it happened starting from yesterday(07/12).

GET
https://api.yelp.com/v3/businesses/search?latitude=37.7873589&longitude=-122.408227&categories=chinese&radius=1600&limit=5&open_at=1499991900&sort_by=rating 

Got **null** latitude and longitude for some of the returned businesses.

**Comment by tomelm** [comment]
@zuchie were these same businesses not returning null before?

**Comment by jrlimtiaco** [comment]
I'm having the same problem. @tomelm yes, businesses that weren't returning null coordinates now are.

**Comment by zuchie** [comment]
@tomelm sorry I don't remember if there are the same businesses, but I did use the same query string and didn't get any nulls before.

**Comment by slmatthiesen** [comment]
Chiming in here too. 
Businesses that previously gave me results (and I was able to create map markers with) are now returning null for the coordinates.
It seems that the number of null coordinates has increased over the last week or so. First saw it last Friday and thought it was a single fluke business.

The amount of null coordinates with a search of 'pizza' in san francisco is very high.

**Comment by mittonk** [comment]
@slmatthiesen , @zuchie , @jrlimtiaco : Could you supply one `business_id` (like `starbucks-san-francisco` that you think changed behavior recently?  Searching for "pizza" in San Francisco shows some businesses that have null lat-lngs for various reasons (some valid), I want to make sure we're investigating the thing that changed recently.

**Comment by zuchie** [comment]
@mittonk give `spartan-taco-truck-san-jose-4` a try.
I remember it was able to return a valid lat-lng until recently.

**Comment by slmatthiesen** [comment]
Escape from New York Pizza has always had a lat long for me:
escape-from-new-york-pizza-san-francisco-3
![escape](https://user-images.githubusercontent.com/2328065/28249369-6d92a21a-6a09-11e7-99ce-7f39125373df.PNG)
But today it does not. I took a screenshot of it null here so that if the coordinates happen to pop back in, I won't look crazy =)

Yesterday, Nizario's pizza nizarios-pizza-san-francisco-2 had null lat long, but today it does have coords.

**Comment by e-jam** [comment]
I have the exact same problem too. This only started 3 days ago and it is causing my entire project to fail. Any ideas as to why this is happening?!!

**Comment by mittonk** [comment]
@zuchie , @slmatthiesen : Perfect, that'll make this investigation much easier.

**Comment by mittonk** [comment]
@zuchie , @slmatthiesen : Both those businesses are showing lat-lngs for me today; @slmatthiesen 's screenshot for the win.

@e-jam : Stellar, let me poke some of those.  (As noted in https://github.com/Yelp/yelp-ios/issues/71 , lat-lngs _can_ be null --- your code should handle that case.  This bug is around the recent increase in frequency.)

**Comment by mittonk** [comment]
I've been able to reproduce the issue, it's indeed sporadic-by-business, digging!

**Comment by mittonk** [comment]
Found the issue, fixing it.

**Comment by mittonk** [comment]
Fixed!  Businesses including `nutrition-house-milpitas` are once again returning lat-lngs.

Thanks @zuchie , @slmatthiesen , @e-jam for all the repro cases --- that was a huge help in tracking this down!

(Again, for the record --- not all businesses return lat-lngs, but this one should.)

**Comment by e-jam** [comment]
@mittonk Thank you for fixing the issue. I took into consideration the fact that businesses can possibly return nil lat / long, and handled that case in code.

**Comment by zuchie** [comment]
@mittonk thanks for the fix.
