### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by johschnei** [Yelp/yelp-fusion#312]
I am fairly new to this, I am trying to get an API address. I got to the page where I get my client ID and client secret I don't know what to do from now. I don't  know  how to do the following:
2-Get an access token using your client id and secret.
3-Authenticate API calls with the access token.
Those are step 2 and 3 in the process of getting an API 
I guess this issue is I don't know  how  to make a Post call with my client ID and client secret
can someone please help?

**Comment by mittonk** [comment]
@johschnei : Have you found the Getting Started and Authentication walk-throughs yet?  Sounds like Authentication is the next thing to read:
* https://www.yelp.com/developers/documentation/v3/get_started
* https://www.yelp.com/developers/documentation/v3/authentication

Does that help?

**Comment by annygakh** [comment]
A good place to get started is https://www.yelp.com/developers/documentation/v3/get_started
On that web page, Yelp provides us with Postman templates for various API calls.

Postman is an application that lets you make various API calls from their Google Chrome browser app or from their native app. This way you don't have to construct raw queries yourself. Postman is helpful when you want to explore some APIs but you haven't decided which framework/language you will eventually use for your app.

If you click on 'Run in Postman', it will load some of common Yelp API calls in your Postman app (see the screenshot, I am using Postman's browser app for Google Chrome). One of them, orange in the screenshot, is the first one you want to try because it gives you the access token which you can use in your later API calls.

<img width="1213" alt="screen shot 2017-10-15 at 11 03 50 am" src="https://user-images.githubusercontent.com/9780809/31587592-46f7c0f4-b199-11e7-9f31-53e53d7aa47e.png">
You have to fill in the values in the client_id and client_secret and then you can click 'Send' (the blue button).

I hope this helps!

**Comment by watterso** [comment]
Closed due to inactivity.
