### ISSUE TITLE
Generate Access token for Yelp api using fetch in React-Native

### ISSUE THREAD

**Issue by aaduru** [Yelp/yelp-fusion#330]
## Overview
- **Client ID:**-qWaHcsd1FNhDOLm5IG1zw
- **Issue type:** Validation Error
- **Summary:** generate access token using fetch in react native
- **Platform:** React Native

## Description
I am new to React Native and trying to make a post request to generate access token. I used postman to make the post request and obtained the access token. 

## More information
I pass the client id, client secret and the grant type along with the endpoint.  The status of the issue is 400 and error message is that client id and client secret is not provided. 

### Endpoint
_'https://api.yelp.com/oauth2/token'

###  function which 
_fetchYelp(){

  let data = {
    method: 'POST',
    body: JSON.stringify({
      'client_id': 'id',
      'client_secret': 'secret',
      'grant_type': 'client_credentials'
    }),
    headers: {
      'Accept':       'application/json',
      'Content-Type': 'application/x-www-form-urlencoded'
    }
  }
  return fetch('https://api.yelp.com/oauth2/token', data)
          .then(response => response.json());

  }

### Response
status   400
 timeout  0 
      response {"error":{"code":"VALIDATION_ERROR",
                "description":"client_id or client_secret parameters          not found. Make sure to provide client_id and client_secret in the body with the application/x-www-form-urlencoded content-type"}}
      response_url https://api.yelp.com/oauth2/token
```

What am i missing here? Thank you for your help.

**Comment by GhostViz** [comment]
Recently Yelp fusion switched from oauth to api keys. See the [documentation here](https://www.yelp.com/developers/documentation/v3/authentication)..

**Comment by rat395** [comment]
I could be wrong but I don't think that the Yelp Fusion API supports getting access tokens like that, or at all, since they no longer provide a client_secret.

Instead, when you make your GET requests, you use the HTTP Header <b>Authorization</b> with the value <b>Bearer YOUR_API_KEY</b>

I haven't used react, but It worked for me when I tried it in python. The sample.py was broken, I'll probably make a pull request to have it working, but I honestly have like no idea of what I'm doing. I just know it works.

<h3>For React (your app)</h3>
This is the header you're going to use for your GET requests, forget about the access token.

headers{
'Authorization':  'Bearer <b>YOUR_API_KEY</b>'
}

*To be clear, YOU_API_KEY is the api key of your app.

**Comment by tomelm** [comment]
@rat395 is correct, api key's are now the preferred authentication method. If you still have your client secret you can still use the token endpoint for a few months but that will be going offline sometime in February (more explicit timeline to come soon).

**Comment by hardagerianil123** [comment]
can any one help me with the new authentication process of yelp in python.

when  i try to use the below code to authenticate

from yelpapi import YelpAPI
yelp_api = YelpAPI('ClientID','API Key')



Traceback (most recent call last):
  File "C:\Users\anil.hardageri\eclipse-workspace\yelp\YelpAllData.py", line 17, in <module>
    yelp_api = YelpAPI('ZMg0OxVCD2haEMxtIHeLQw','izo1_rOzKg373Up3Wz8vNR35XF-3dD88TUNGHB1R1TwEFsBtaCCO8nA0GyadUgLu0fw8z4Jo9fbiR2PR-ulBHWNVGg3Fjyl98W0b29YpE3F7n_8u1sZifg-UXD4rWnYx')
  File "C:\Users\anil.hardageri\AppData\Local\Programs\Python\Python36\lib\site-packages\yelpapi\yelpapi.py", line 64, in __init__
    self._yelp_session.fetch_token(token_url=ACCESS_TOKEN_URL, client_id=client_id, client_secret=client_secret)
  File "C:\Users\anil.hardageri\AppData\Local\Programs\Python\Python36\lib\site-packages\requests_oauthlib\oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\anil.hardageri\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 408, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\anil.hardageri\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\anil.hardageri\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 389, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.


i get the following error.  Any help is highly appreciated

**Comment by hardagerianil123** [comment]
@rat395 can you please share your python code to authenticate using API KEY.i have issue authenticating using the below code.

from yelpapi import YelpAPI
yelp_api = YelpAPI('ClientID','API Key')

**Comment by rat395** [comment]
@hardagerianil123 oh dude first and foremost, you should always keep your API Key hidden!! The bad news is that the "yelpapi" library no longer works! Since Yelp doesn't use OAuth2 to authenticate Yelp HTTP requests! The good news is that using the Yelp API without the "yelpapi" is actually pretty easy.

[https://github.com/rat395/yelp-fusion/blob/master/fusion/python/sample.py](url)

checkout this sample app. Its the same one as the one from this repository, but I fixed it up.
It may seem a little complicated at first, but just read through the docs for each function and it will make sense. If you have any further questions please ask!

**Comment by virgytam** [comment]
Hi @hardagerianil123, are you still having issues with authentication? The "yelpapi" library that you're using is not an official Yelp library and hence we can't help with that. You can try raising issues in that particular project's repository.

**Comment by dan98765** [comment]
@rat395 thanks for calling out that API Key should always stay hidden. It's fine to share your client ID, but please never post your API Key publicly. @hardagerianil123 I've reset your API Key just now. 

This issue was originally filed re: the now-deprecated oauth2 token credential flow, so I'm closing it out.
