### ISSUE TITLE
Getting 502 Error from sending a business request with an id that contains accented vowels

### ISSUE THREAD

**Issue by floydw1234** [Yelp/yelp-fusion#344]
## Overview
- **Client ID:**  Z5PFrUTPBH
- **Issue type:** Server not responding to requests with accents
- **Summary:** The API seems to not handle accents on vowels in the id of a business info request
- **Platform:** JS API

## Description
Expected the normal response from the business API but got the 502 bad request

### Endpoint
Fusion Search API

### Parameters or Sample Request

https://api.yelp.com/v3/businesses/café-momentum-dallas-2

### Response
Unhandled rejection StatusCodeError: 502 - "<html><body><h1>502 Bad Gateway</h1>\nThe server returned an invalid or incomplete response.\n</body></html>\n"

**Comment by dlgallagher** [comment]
@floydw1234 thanks for the issue; in the past we've had issues making sure unicode char input works but it has been some time since then-- I'm hoping there has not been a regression.

I just did a quick attempt to repro on https://api.yelp.com/v3/businesses/café-momentum-dallas-2 and got back a valid response:
```
{
	"id": "café-momentum-dallas-2",
	"name": "Café Momentum",
        ....
}
```
Could you please re-try and see if the issue still occurs?

**Comment by CLClark** [comment]
@dlgallagher Hi, I came across this thread from a Google search; I'm experiencing a similar issue.
id: héritage-fine-wines-beverly-hills

Requesting via node.js HTTPS module:
The yelp endpoint responded with 304 status, however the response body contained "502 Bad Gateway".
Requesting via Firefox:
_https://api.yelp.com/v3/businesses/héritage-fine-wines-beverly-hills_
GET https://api.yelp.com/v3/businesses/h%C3%A9ritage-fine-wines-beverly-hills
My browser executes the request with percent encoding, which is why the yelp API may appear to accept
the accented char in a request.

I solved it on my end by percent-encoding my GET to the yelp endpoint,
 but I still get an error when requesting (https://api.yelp.com/v3/businesses/) with an unencoded é character

**Comment by dlgallagher** [comment]
Thanks for the followup @CLClark! Percent encoding is indeed the way to go. 
The example in the original: https://api.yelp.com/v3/businesses/caf%C3%A9-momentum-dallas-2 would be what should actually be sent. 

I've filed a ticket internally to look at how we can improve our docs & the api's handling of unicode chars like this.

**Comment by dan98765** [comment]
I'm closing out some older issues that appear resolved or stale. Please comment there is still an issue.
