### ISSUE TITLE
Inconsistent Results based on City/State

### ISSUE THREAD

**Issue by metallurgix** [Yelp/yelp-fusion#349]
## Overview
- **Issue type:** Question, Bug
- **Summary:** The search API results are very inconsistent when searching for businesses based on State or City.
- **Platform:** Web-API

## Description
I would like to fetch all the businesses under the category of 'electricians' in the state of Georgia(US). When I use the search API endpoint, I receive a total of 129 results. However, when I try to search for a city within Georgia i.e. Atlanta, I receive 215 results. This is consistently seen across various other cities like TX vs Dallas, where the city Dallas gives more results compared to the state of Texas.

### Endpoint
https://api.yelp.com/v3/businesses/search

### Parameters or Sample Request
Request 1: https://api.yelp.com/v3/businesses/search?location=Georgia&categories=electricians
Request 2: https://api.yelp.com/v3/businesses/search?location=Atlanta&categories=electricians

### Response
Response 1: {"total":129,...}
Response 2: {"total": 215,...}

**Comment by Valectar** [comment]
The search is limited by a radius around a search location, so when you do a search on a state, you are actually searching in a radius from the center of the state. Since the maximum radius is about 25 miles, even at max radius you will only be searching a small portion of the whole state (depending on the state, anyway). When you search in a city, your radius is in a much more densely populated area, so you're likely to get more results than you will searching on a state.

**Comment by metallurgix** [comment]
That explains the inconsistency. Thank you for the info.
