### ISSUE TITLE
[Question] As a business owner, can I not retrieve all reviews for my business?

### ISSUE THREAD

**Issue by brandonreid** [Yelp/yelp-fusion#36]
Is there a way to retrieve all the reviews for a business if I have credentials or an access token of some sort? Or is this just off limits?

Is there a way to pay for this privilege?

**Comment by guangyang** [comment]
Sorry that we don't offer a way to return all reviews of a given business. I'd love to understand what you are trying to achieve by getting all reviews though so that we can see whether there is any other way we can help.

**Comment by brandonreid** [comment]
We've got a startup where we collect customer feedback for restaurant chains. We offer a few data collection methods. Our customers really value yelp reviews and a few have asked if we can show them in our UI so it's all in one place and they can take action on stuff that comes up, like they do with data they collect with our tools. Restaurant owners really value yelp reviews.

**Comment by tannerm** [comment]
I am building a website for a client who would like to aggregate reviews from Yelp! and Google Places. Being able to pull all reviews would be super helpful. If that is not possible, could the API be updated to return the 3 most recent reviews? Right now it seems to pull the 3 oldest reviews.

**Comment by alextrs** [comment]
The same here. We build web platform for restaurants and they would like to have one place to go and see all reviews for their business (Yelp, Google, Facebook, TripAdvisor and etc).

**Comment by bizmate** [comment]
this has been like this for all versions of the apis, in V2 they limited reviewes to only 1, at least now it returns up to 3

**Comment by alextrs** [comment]
yeah, 3 would be enough if you can keep them (just pull reviews once every hour and merge to your own database to display), but APIs agreement doesn't allow you to do it. People are generally very busy to just sit a wait when new review comes up, so it's not reliable, as more than 3 reviews can be created since the last visit.

**Comment by thatguyyoulove** [comment]
This feature would be quite beneficial to our company. We provide reputation-based reports for the major review services in an area of our product. Recently, Google launched their 'My Business' API which, among other things, allows one to pull all of their own reviews, and reviews for any other google account which has authorized them to do so. In this way you can limit programmatic access to reviews that are owned by you or your clients rather than being able to blindly pull any public page's reviews.

Without something similar in Yelp, we can really only push our customers to use and monitor Google Reviews. If we had an option in Yelp to get customer data, then we could actually promote its services...

**Comment by mittonk** [comment]
@thatguyyoulove : Your use case might be a better match with
* https://www.yelp.com/knowledge

rather than with the Yelp Fusion API.  Have a look!

@alextrs , @brandonreid : Might also work for you.

**Comment by mfranchitti** [comment]
We have had a few clients approach us about centralizing their review management systems into a single platform, and I have two suggestions for your API to make it easier for businesses to accomplish this:

1) Add a callback for when new reviews are added to a business (perhaps with some requirement on what triggers the callback: IE: review of 3 stars or less). 
2) Allow  business owners to reply to a review with a particular ID. 

These would obviously be available specifically to verified business owners.

**Comment by quytennis** [comment]
@brandonreid  @mfranchitti @alextrs @thatguyyoulove  - please goto https://www.yelp.com/developers/ and click on "Premium Access" and fill out our form so we can follow up on your requests.

**Comment by thatguyyoulove** [comment]
Already tried.

The response I got was:
"Unfortunately, given our limited resources, today we only support larger platforms with at least 10,000 small businesses."

I have around 1,000 businesses that I manage.

**Comment by quytennis** [comment]
@thatguyyoulove  Sorry, we're currently focused on larger platforms at the moment.

**Comment by notflip** [comment]
What are the requisites to get more than 3 review? Thank you.

**Comment by sylow** [comment]
Only focusing on larger platforms means no support for startups?

**Comment by mecca831** [comment]
I am helping a client pulling business owner data (reviews, metrics, etc.) from Yelp. What's a good way to do this? I wrote to request access to Yelp Knowledge API but no one responded. Is there a minimum requirement?

**Comment by kelvinau** [comment]
I actually don't need all reviews for a business. I just want my own personal reviews. Is there any API for getting reviews of my personal account?

**Comment by usfslk** [comment]
It's pointless to create an endpoint for reviews if we only get three of them

**Comment by ctessmer** [comment]
It's crazy that in 2019, Yelp—the leading review platform in the world (pretty sure)—doesn't allow devs to get all reviews programatically. Why? This would make Yelp so much more valuable (and intertwined with businesses.) 

Like so many others wrote, my clients want to aggregate all their review data on their *own* site instead of asking their customers to hunt them down on the various review platforms (Google, Yelp, etc).

Please Yelp, make this happen. My clients would gladly pay for this.

**Comment by ypicard** [comment]
I support this feature request.

**Comment by Arametheus** [comment]
Yes please Add this feature to pull all reviews with Responses. So my clients can quickly see ones that need to be Responded too.

**Comment by skunkbad** [comment]
I'm here to ask for more reviews too. Just a small business owner that would like to display 3 reviews on each page of my website... but just not the same 3 reviews. Displaying the same 3 reviews on all pages doesn't look good and is pointless.

**Comment by usfslk** [comment]
Hi robert let me know, I can fix your issues on the website

**Comment by vastava** [comment]
At least let us sort the reviews by date or some other metric so we have some control over the 3 reviews the API returns
