### ISSUE TITLE
Open_at returning Zero Yelp businesses

### ISSUE THREAD

**Issue by aliguan** [Yelp/yelp-fusion#371]
We are hitting the endpoint: 

https://api.yelp.com/v3/businesses/search?latitude=28.538336&longitude=-81.379234&open_at=1519354549

The API returns businesses open at the given time one or two days in the future, but greater than that, no businesses are returned. For example, if we hit the endpoint for tomorrow, businesses will be returned. However, if we hit the endpoint for 5 days from now, no businesses will returned.

Problems we thought of:
- We have double checked the unix time and used various times such as 9:00 am, 12:00 pm, etc at these endpoints and still received no businesses open.
- We have used Postman to hit the endpoint and it also gives us no businesses when it is greater than 2 days in the future.
- We made sure time stamp is an integer, not string

**Comment by sw3196** [comment]
I also meet the same question as described above. I am sure the integer of time stamp is correct and we can easily check the open at time on today. But two days or more in the future, it doesn't work. Could anyone figure out the problem?

**Comment by wangzonghen9** [comment]
Same problem

**Comment by maulikmmodi** [comment]
I am also facing the same issue, did anyone have the solution for this?

import requests

url = "https://api.yelp.com/v3/businesses/search"

querystring = {"term":"indian%20restaurants","location":"brooklyn","categories":"mexicun","open_at":"1555614000","limit":"3"}

payload = ""
headers = {
    'Authorization': "Bearer 7NjA90modOdaeEn6bLkfmOoy3YIibnWpCUki41GqXzW5z0nlxHPwRpjXeAJ1ycwHd0qeiipWT-9vtxH-WcSdM5zj9TcHhJrEzW6n_4tuQCS5YHUOnmvg_Ax4KYmKXHYx",
    'cache-control': "no-cache",
    'Postman-Token': "99ffddfa-bc56-4f2e-9d2e-1262bc2ca155"
    }

response = requests.request("GET", url, data=payload, headers=headers, params=querystring)

print(response.text)

**Comment by RonaldSwaine** [comment]
Found this Issue while having the same problem as others, but have since resolved it.

The documentation on this is not clear. If you provide it with a timestamp a long time ago, you'll see the issue. **You must provide a timestamp that's within the _last two weeks_ of the request's time.**

Since businesses can have different times on each day, I presume its taking the day of the week into consideration as well - not just the time.

For general use, like determining if a business is "open late", I would tend to just pick any regular business day within the last 2 weeks.
Be careful of holidays potentially affecting this response. Without further details on what the logic really is, its hard to know what issues could arise.

**Comment by RipTheJacker** [comment]
This needs to be updated in the documentation. It does not work for selecting businesses that will be open "at X time" as the documentation suggests.

**Comment by JOyo246** [comment]
@RipTheJacker my solution will be to check if the date picked is before this coming Sunday. If it is, then that's our date..If not, subtract 604800 seconds (one week)
