### ISSUE TITLE
v3 api authentication issue

### ISSUE THREAD

**Issue by gregorybessoni** [Yelp/yelp-fusion#383]
Hi,
I have checked the yelp api currently  using v3 version of api. Now according to v3  authenticate process is to create the app and get the api key from app. we just need only api to authenticate. but when I am trying to run any endpoint. I am getting following error.

    [error] => stdClass Object
        (
            [code] => TOKEN_INVALID
            [description] => Invalid access token or authorization header.
        ) 

Hi, I am usting this code 
<?php

 $DEFAULT_TERM = "food";
$DEFAULT_LOCATION = "San Francisco, CA";
$SEARCH_LIMIT = 3;
$params = array(
	"term" => $DEFAULT_TERM,
	"location" => $DEFAULT_LOCATION,
);
$prm =  http_build_query($params);
 $api_key = 'API key';
 //$header = array("Authorization: Bearer ".$api_key);
$ch = curl_init();

//set the url
curl_setopt($ch,CURLOPT_URL, "https://api.yelp.com/v3/businesses/search?term=delis&latitude=37.786882&longitude=-122.399972");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET"); 

curl_setopt($ch,CURLOPT_RETURNTRANSFER, TRUE);
 curl_setopt($ch,CURLOPT_HTTPHEADER, array(
        "authorization: Bearer ".$api_key
    ));
$result = curl_exec($ch);
$http_status = curl_getinfo($ch);
curl_close($ch);
 echo "<pre>";
 print_r($http_status);
if($result){
   $data = json_decode($result);
   echo "<pre>";
   print_r($data);
  
}
?>

please let me know where i am doing wrong. I am getting 401 error

http://www.myreviewswidget.com/yelp/apitest.php

**Comment by virgytam** [comment]
Hi gregorybessoni, it looks like the API key value you're supplying in your request is invalid. I see in your code that you have `$api_key = 'API key'` and you're using this value in your request. You need to use the API Key we've generated in the Manage App page: https://www.yelp.com/developers/v3/manage_app

**Comment by gregorybessoni** [comment]
Hi, 
I using api key from my account  in place of "API key" . in above code i have not mention the api key so i just write it as "API key" .  Using api I am getting same error . you can check the link where i am getting error.
http://www.myreviewswidget.com/yelp/apitest.php

Please help
Thanks

**Comment by virgytam** [comment]
I'm seeing a different error in your latest error status -- TOKEN_MISSING. Can you confirm that the API key is in the header and that it's a 128-character string?

**Comment by ejrivera6** [comment]
Hello Virgytam,

I am using Postman, I have my API key in Headers with Bearer API_KEY as the value and the key as, well, the key. This is my error, what am I doing wrong?

{
"error": {
"code": "OAUTH_TOKEN_ENDPOINT_DEPRECATED",
"description": "The oauth2 token endpoint has been deprecated and removed; you must use your API key for authentication instead. Please see https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going for info & migration steps"
}
}

**Comment by antimtechnology** [comment]
Hello @virgytam 

I got same same error "Token Missing" and i am using 128 character string as well from my manage app.. Please tell me how can i solve this error.... And if possible please tell me steps to get access token..

As i am finding token from post man i got error that it is depricated... 



Looking forward for you Reply... Thank you...

**Comment by pmdbt** [comment]
Hi @virgytam 

I am having the same issue as antimtechnology. I basically copied the code you guys have here on GitHub for python and modified some parts. I have attached the code in question as a .py file inside a zip folder. When I run the code, I receive this error:

Querying https://api.yelp.com/v3/businesses/search ...
{'error': {'code': 'TOKEN_MISSING', 'description': 'An access token must be supplied in order to use this endpoint.'}}

This is very confusing because I thought that the Token was deprecated for v3 of the API, yet all the search endpoints insists I still need one. In my attached file, I did not include my actual API key. Instead I just left it as 'API_KEY', but I double checked my actual key and it is in fact a 128 character string. 

Do you see what is causing this error? If not, would you recommend I obtain a new API key? 

[Test_Code.zip](https://github.com/Yelp/yelp-fusion/files/2018996/Test_Code.zip)

**Comment by dan98765** [comment]
@pmdbt I downloaded your zipfile, edited it to remove the pandas/matplotlib/etc and just print `rez` out then ran it. Output:
```
Querying https://api.yelp.com/v3/businesses/search ...
{'city': [u'Los Angeles'], 'name': [u'Bottega Louie'], 'rating': [4.0], 'longitude': [-118.32138061523438], 'state': [u'CA'], 'latitude': [34.0615895441259]}
```
It seems to work fine. I suggest checking that you've copied over your API Key fully. If that still doesn't work, could you post what your Fusion client ID is? This is the 22-character string above your API Key on the [Manage App](https://www.yelp.com/developers/v3/manage_app) page.

**Comment by pmdbt** [comment]
@dan98765 Thanks man! I got it to work as well. It turns out that if you have an API Key from before the API deprecated the Token requirement, then the API still asks for a token. I updated my API key, and there have been no issues with the new one. I recommend anyone else who is running into the same error to update their API key as well.

**Comment by dan98765** [comment]
@pmdbt awesome, glad to hear it's working now, and thanks for following up with the suggestion to help others who may hit the same problem and find this issue via google or whatever. 👍
