### ISSUE TITLE
Responses do not contain 'RateLimit-Remaining' header after rate limit is reached.

### ISSUE THREAD

**Issue by gideonaa** [Yelp/yelp-fusion#388]
## Overview
- **Issue type:** Improvement suggestion
- **Summary:**  My application checks the response headers to check how many calls are left in RateLimit-Remaining. Once there are no longer any calls remaining, the response contains RATE_LIMIT_REACHED message in the body but the RateLimit-Remaining header is no longer present in the response. But I think it would be reasonable and expected behavior for RateLimit-Remaining=0 to remain in the headers on subsequent responses.

## Description

My application logic is something like:
```
if (int(response.headers['RateLimit-Remaining']) == 0):
        raise APILimitReached
```

However, this graceful shutdown will never occur since at 0, the header disappears, causing a KeyError. I'll simply change it to `==1`  (and miss out on that final call 😄), but thought I'd give this suggestion. Hope it helps!

### Endpoint
_(e.g. Fusion Search API /Match)_

**Comment by dan98765** [comment]
This idea totally makes sense, thanks @gideonaa. I'll file it internally and see what we can do.

**Comment by dan98765** [comment]
We've just pushed out a change that should add the access limit headers into 429 responses thrown due to being at or over your daily limit. Please let us know if you see any unexpected behavior.

Also note that this change only affects the 429 errors caused by being over your daily limit. 429 errors caused by making too many requests per second still do not contain these headers (we're working on adding them to those responses also in future). The 2 different reasons for returning a 429 are described on https://www.daniellg.dev.yelp.com/developers/documentation/v3/rate_limiting

**Comment by gideonaa** [comment]
@dan98765 awesome! Ya'll are lightening fast! I'll let you know if I spot anything else.
