### ISSUE TITLE
matches endpoint not returning results

### ISSUE THREAD

**Issue by kryptklast** [Yelp/yelp-fusion#412]
## Overview
- **Client ID:** Xe86ePA8e1cu442gz_xxCw
- **Issue type:** bug
- **Summary:** I'm attempting to use the https://api.yelp.com/v3/businesses/matches endpoint but getting no results. I can query other endpoints and get the results I expect, but just get an empty list when querying matches.
- **Platform:** Desktop-Python and Chrome-Postman

## Description
When I query the matches endpoint I don't get results. For example, https://api.yelp.com/v3/businesses/matches?name=kolam&city=Newtown&state=CT&country=US gives me

```
{
    "businesses": []
}
```
Other endpoints return the result I'd expect. For example, https://api.yelp.com/v3/businesses/kolam-newtown gives me the business information, and https://api.yelp.com/v3/businesses/search?term=indian&latitude=41.3608908&longitude=-73.2663687 (where the lat lng is the location of "Kolam") returns a list of Indian restaurants with Kolam first.

### Endpoint
Fusion Business Matches API
/businesses/matches
https://api.yelp.com/v3/businesses/matches

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/matches?name=kolam&city=Newtown&state=CT&country=US

### Response
```
{
    "businesses": []
}
```

Thanks for taking a look! The old enpoint, https://api.yelp.com/v3/businesses/matches/best, also doesn't return results for me.

**Comment by kryptklast** [comment]
Excellent, thanks! I can use the address1 param. Recommend noting in the documentation that if the required parameters do not return results, adding more specificity (as in using address1) will likely help.

**Comment by dan98765** [comment]
@kryptklast thanks for the suggestion! We're considering whether to just update the documentation, or whether to just make address1 a required input parameter and throw a validation error if it's not included since the results do not make much sense without it currently. We'll update https://www.yelp.com/developers/documentation/v3/business_match either way once a decision is made.

**Comment by dan98765** [comment]
@kryptklast just to close the loop: today we've made `address1` a required field for the Business Match endpoint, in order to make it clearer to users what the usefulness of that endpoint is. Note that the empty string "" can still be passed in for `address1` to explicitly match businesses without an address1. [Here's the changelog entry](https://www.yelp.com/developers/v3/changelog#changelog-20180508).
