### ISSUE TITLE
sort_by desc for reviews api

### ISSUE THREAD

**Issue by shayts7** [Yelp/yelp-fusion#418]
## Overview
- **Client ID:** 
- **Issue type:** question
- **Summary:** sort reviews from newest to oldest
- **Platform:** linux

## Description
I'm using **businesses/{id}/reviews** API and noticed there is a possibility to sort the results according to date by using the **sort_by=time_created** query param, but the default is **asc**, means oldest to newest.
I would like to use it **desc** is it possible?

### Endpoint
Fusion Search API

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/{any id}/reviews?sort_by=time_created
```

**Comment by teekwak** [comment]
Hi @shayts7,

We sort the reviews by the following:
https://www.yelp-support.com/article/How-is-the-order-of-reviews-determined?

Currently, we only support the "locale" parameter for the reviews endpoint. Since we return up to 3 reviews, I suggest writing a short script that will parse the "time_created" values for each of the reviews returned and sort in descending order.

**Comment by shayts7** [comment]
@teekwak  Thanks for the answer!

**Comment by webmarketingsmart** [comment]
I think it is important to be able to call the reviews by the post date. I understand it is limited to calling 3 reviews, but sorted by "Yelp Sort." For analytics reasons, it will be the best to get the top 3 latest reviews posted (not including the filtered reviews). Sometimes, the "Yelp Sort" changes the order and we get what we already have processed and often behind the date it was posted. 

Please let me know if there is an alternative way of calling the top 3 latest reviews or if it is included in the future development for the Fusion API.

Thank you!

**Comment by Josh979** [comment]
How is sorting reviews still not a thing?
