### ISSUE TITLE
Syntax error YLPClient.aprove

### ISSUE THREAD

**Issue by TylerWanta** [Yelp/yelp-fusion#424]
## Overview
- **Client ID:** 
- **Issue type:** Syntax Error
- **Summary:** Getting a syntax error in the provide code about yelp's api
- **Platform:** IOS - swift 4

## Description
When implementing the code provided in YLPClient+Future.swift , i'm getting a syntax error in YLPClient.aprove. The error is "Instance member 'authorize' cannot be used on type 'YLPClient'; did you mean to use a value of this type instead?" When changing YLPClient to self, the error goes away but a new one appears, "Extra argument 'completionHandler' in call". 

Does anyone know a fix for this? This seems to be the only documentation on Yelp's api.

**Comment by akun1** [comment]
Not sure if this helps, but I was having trouble with the .authorize() function. It was because it doesn't exist anymore in the API. However, the example project provided by Yelp uses it. 

To create a Yelp client object to make calls from, use:

`let client = YLPClient.init(apiKey: yourApiKey)`

Once you make this object, you can make calls from it.
