### ISSUE TITLE
REQUEST_TIMED_OUT for multiple graphql queries and the api very slow in general

### ISSUE THREAD

**Issue by biancazzurri** [Yelp/yelp-fusion#425]
## Overview
- **Client ID:** 2bHSZhM0huV8LRh3YHaOSQ
- **Issue type:** bug
- **Summary:** REQUEST_TIMED_OUT returned for query with more than 1 graphql query, and in general the API is very very slow - took 30 seconds to get replies for 10 simultaneous queries
- **Platform:** any platform

## Description
Since today the api is very very slow and replies ok to query with only one graphql query

**Comment by virgytam** [comment]
Hi @biancazzurri , can you provide a sample of a query that is slow and times out?

**Comment by coolboiime** [comment]
I got the sane issue. My app is in production, and users are complaining about it.

`{ error: 
{ code: 'REQUEST_TIMED_OUT',
description: 'The request timed out, please try again later. If this continues, please create an issue on GitHub with the request you\'re making: https://github.com/Yelp/yelp-fusion/issues' } }`

**Comment by coolboiime** [comment]
This is running within AWS Lambda function. When you request the API one before one finishes, this most likely happens. You can ignore the header logs, they are for my reference only.

<img width="1411" alt="screen shot 2018-06-17 at 11 33 19 pm" src="https://user-images.githubusercontent.com/9779803/41517191-121d68ac-7287-11e8-8ce9-cd4b35c542ec.png">

**Comment by watterso** [comment]
@coolboiime your issue, while also about performance seems closer to whats going on in #430 see my comment there for ideas about addressing your issue

**Comment by coolboiime** [comment]
@watterso Trying similar queries might not be an option for me. I use all the information I can get from a single graphql request. I don’t think I have included any of the IDs because it’s not used anywhere in the app I made.

The timeout issue isn’t a bug issue, I suppose I can wait for a fix. Although, if the app continues with random timeouts because of increased usage, not sure what to do then.

**Comment by coolboiime** [comment]
Also I noticed that when I set the `price` parameter to `1,2,3,4` instead of `1, 2, 3, 4`, the API will return an error:

`
{"errors":[{"message":"{'error': {'code': 'INTERNAL_ERROR', 'description': 'Something went wrong internally, please try again later.'}}","locations":[{"line":3,"column":6}]}],"data":{"search":null}}
`

**Comment by watterso** [comment]
@coolboiime that does look like a bug on our end, could you file a new issue so that it doesn't get lost?

**Comment by coolboiime** [comment]
@watterso Sure thing, just had to make sure this wasn’t related to the bug you pointed at earlier.
