### ISSUE TITLE
Question on storage of business names

### ISSUE THREAD

**Issue by hhz1001** [Yelp/yelp-fusion#426]
Apologies if this is not the correct place for this question - I'm new to the Yelp Fusion API, and have a question around the API Terms of Use that I wanted to clarify before I proceeded too far. 

Does storing just a list of business names obtained through the API, associated with respective business IDs, for longer than 24 hours violate the following part of the Terms of Use?

_You agree that you will not, and will not assist or enable others to cache, record, pre-fetch, or otherwise store any portion of the Yelp Content for a period longer than twenty-four (24) hours from receipt of the Yelp Content, or attempt or provide a means to execute any "bulk download" operations, with the exception of using the Yelp Content to perform non-commercial analysis (as further explained below) or storing Yelp business IDs which you may use solely for back-end matching purposes_

My current understanding is that this is not allowed, since the business name data seems to fall under the definition of Yelp Content. In that case, is the preferred approach to a) store only the relevant business IDs and then b) re-query the API to pull the business names every time they're needed? I've seen that the GraphQL API would allow doing this with a single query for a set of multiple business IDs, but I wanted to check whether this would be absolutely necessary.

Thanks for your help in advance.

**Comment by watterso** [comment]
@hhz1001 your understanding is correct. Please do not store anything except for business ids for more than 24 hours. This is so that users that view data coming from an API integration will always be presented with the freshest yelp data.

As far as implementing to logic to achieve this, using a graphql query for multiple business ids is one way to achieve that, but multiple calls to the [business endpoint](https://www.yelp.com/developers/documentation/v3/business) works too!

**Comment by hhz1001** [comment]
Great, thank you for the confirmation!
