### ISSUE TITLE
REQUEST_TIMED_OUT consistently returned for certain GraphQL queries

### ISSUE THREAD

**Issue by KatMaff** [Yelp/yelp-fusion#430]
## Overview
Client ID: 8lgIUAzFnZItmgJ-fpHjXg
Issue type: bug
Summary: REQUEST_TIMED_OUT consistently returned for certain graphql queries, but the request succeeds if you change the query slightly. 
Platform: any platform

## Description
For certain locations, searching by category, I almost always get REQUEST_TIMED_OUT, however small changes to the query, like a minor change to the lat/long values, or removing the "reviews {text}" attribute, can make the query succeed.

### Endpoint
https://api.yelp.com/v3/graphql

### Parameters or Sample Request
{
    search(latitude: 40.7533, longitude: -73.9838, categories: "coffee", limit: 50, sort_by: "distance", radius: 40000) {
        business {
			name id alias url rating display_phone distance review_count photos categories {
				alias
			}
			coordinates {
				latitude longitude
			}
			location {
				address1 city state zip_code country
			}
			reviews {
				text
			}
		}
	}
}

### Response
{"error": {"code": "REQUEST_TIMED_OUT", "description": "The request timed out, please try again later. If this continues, please create an issue on GitHub with the request you're making: https://github.com/Yelp/yelp-fusion/issues"}}

## Extra information
An almost identical query (without reviews {text}) succeeds:
{
	search(latitude: 40.7533, longitude: -73.9838, categories: "coffee", limit: 50, sort_by: "distance", radius: 40000) {
		business {
			name id alias url rating display_phone distance review_count photos categories {
				alias
			}
			coordinates {
				latitude longitude
			}
			location {
				address1 city state zip_code country
			}
		}
	}
}

**Comment by watterso** [comment]
Hey @KatMaff I'd highlight this part of your report

> An almost identical query (without reviews {text}) succeeds

Our graphql API is still in its relative early days so it is not nearly as performant as our traditional REST API, so some queries will timeout because loading various parts of the data is more or less performant. In this case I would ask if you _really_ need all the data you are requesting in this query at the same time. 

An example API integration might surface search results to an end user (with a slimmed down version of your query) and then when the end user selects a specific business the API integration would make a GraphQL business call requesting data such as address, url, reviews, etc.

Of course the performance of GraphQL is on our mind, but when it will get worked on I can't say, but in the mean time I would suggest exploring getting by with splitting what data you request between separate search and business calls.

P.S if you'd like to try your queries before they are in your code check out our web-based [graphql console](https://www.yelp.com/developers/graphiql)

**Comment by KatMaff** [comment]
Thanks for the suggestion. I think that workaround will be suitable for now.

**Comment by coolboiime** [comment]
Just to add-on, the issue seems to be getting worse. I got 13 `REQUEST_TIMED_OUT` errors in the past 8 minutes.
