### ISSUE TITLE
Setting PRICE, LATITUDE, LONGITUDE parameters the wrong way returns Server Code 200 w/ no data.

### ISSUE THREAD

**Issue by coolboiime** [Yelp/yelp-fusion#432]
## Overview
- **Client ID:** jyHeS_MVualewtI_Ab4wHg
- **Issue type:** bug
- **Summary:** Setting `price` parameter the wrong way returns server code 200 and no data.
- **Platform:** node-fetch (via React Native)

## Description
I noticed that when I set the `price` parameter to `1,2,3,4` instead of `1, 2, 3, 4`, the API will return an error with a server code of 200.

### Endpoint
GraphQL Search API

### Parameters or Sample Request
```
https://api.yelp.com/v3/graphql
```
POST body:
```
{
	search(term: "Restaurants", latitude: 40.747479, longitude: -73.98722, open_now: true, price: "1,2,3,4", radius: 10000, limit: 35) {
		business {
			name
			is_closed
			url
			phone
			display_phone
			review_count
			rating
			price
			photos
			distance
			attributes
			categories {
				title
				alias
			}
			location {
				address1
				address2
				address3
				city
				state
				zip_code
				country
			}
			coordinates {
				latitude
				longitude
			}
			hours {
				is_open_now
				open {
					day
					start
					end
					is_overnight
				}
			}
			reviews {
				text
				rating
				user {
					image_url
					name
				}
				time_created
				url
			}
		}
	}
}
```

### Response
<img width="1173" alt="screen shot 2018-06-24 at 1 27 23 pm" src="https://user-images.githubusercontent.com/9779803/41821718-8eb79a56-77b2-11e8-9345-b8ce002266c0.png">

## Extra information
1. Setting the price parameter a different way should not throw this kind of error.
2. Throwing this kind of error should return a server code 500, not 200.
3. The errors are not parsable using `JSON.stringify()` (without replacing characters) because they're not really JSON due to the string characters being `'` instead of `"`.

**Comment by coolboiime** [comment]
In addition, if you try to set `latitude` to `0`, and `longitude` to `180`, the same error happens.

**Comment by dan98765** [comment]
@coolboiime thanks for the detailed bug report! I'll file a ticket internally and start looking into this.

**Comment by dan98765** [comment]
@coolboiime looks like there are 3 bugs in our systems you've identified here:

1. price filter with spaces causes server error
2. latitude=0.0 causes server error
3. the error message not being parseable as valid json

I'm deploying the fix for #1 right now, should be live in a couple minutes. #2 is in code review, and I'll fix #3 later today or tomorrow. 

Thank you so much again for the great bug report!

One other thing - currently the graphql api tries to return a response with a 200 status code in all cases except for authentication errors. In the body of the graphql api response there is an `errors` list like you see in the output you posted; in this errors list we will dump the errors encountered while executing your graphql query. Whenever possible we will try to return as much of the query result as possible, even if there are errors encountered along the way. We are somewhat inspired by github's graphql API in how we think about errors. 

As you've seen, since Yelp's GraphQL API is still young and rough around the edges there are plenty of bugs to be discovered and fixed. In addition, if you're ever unsure whether some behavior is a bug or expected (especially if our docs don't specify) then please file an issue so we can fix the API or fix the docs.

**Comment by coolboiime** [comment]
Hey Dan, thanks for getting back to me so quickly!

It’s funny thinking how the GraphQL API trues to return a response with a 200 status code, especially with no data because initially, the app that I wrote told me there was no nearby locations, which confused me for a second.

So I had to write another error catcher after the response code was 200, which was unexpected in this case. In my opinion, if the data was still available, I wouldn’t mind console logging those errors quietly.

I just thought it was weird since it ended up in that place!

**Comment by dan98765** [comment]
> latitude=0.0 causes server error

This fix is now live also; I checked that:
```
{
  search(term: "Restaurants", latitude: 0, longitude: 180, radius: 10000, limit: 35) {..OMITTED..}
}
```
no longer errors out.

**Comment by coolboiime** [comment]
thanks!!!

**Comment by dan98765** [comment]
For 3:
> the error message not being parseable as valid json

I can just make it valid JSON with the quotes escaped... but on further thought I'm now leaning towards just changing the outputs to be more string-like.

Instead of:
```
{
	"errors": [
		{
			"message": "{'error': {'code': 'LOCATION_MISSING', 'description': 'You must specify either a location or a latitude and longitude to search.'}}",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			]
		}
	],
	"data": {...data goes here...}
}
```
The output would be more like:
```
{
	"errors": [
		{
			"message": "LOCATION_MISSING: You must specify either a location or a latitude and longitude to search.",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			]
		}
	],
	"data": {...data goes here...}
}
```
This feels a bit more in-line with other graphql implementations out there. We'd have the error string format be "CODE: DESCRIPTION".

**Comment by coolboiime** [comment]
I actually like it the way Yelp does it. Meaning that it shows the error code and the description separately.

The reason why is because I can write a `switch` statement and customize the error message instead of actually displaying the entire error since the user can't do much on their end.

And a plus is that I get to customize the error messages, making them less scary!

**Comment by dan98765** [comment]
@coolboiime OK I hear you... so you'd prefer just the message as-is, but jumped to json. How about:
```
{
	"errors": [
		{
			"message": "{\"error\": {\"code\": \"BUSINESS_NOT_FOUND\", \"description\": \"The requested business could not be found.\", \"id\": \"yelp-san-franciscoo\"}}",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			]
		}
	],
	"data": {
		"business": null
	}
}
```

**Comment by coolboiime** [comment]
Oh, I forgot you had to escape the double quotes!!

Apparently, after your example, I think I'm also going to side with you too on the error messages being `CODE: DESCRIPTION`, and comparing it actually makes `CODE: DESCRIPTION` look a lot cleaner.

Just to clarify, this applies to GraphQL only and not the default Yelp 500 errors.

**Comment by coolboiime** [comment]
@dan98765 Let me know when you make changes to that specific code, so I can update my app to catch these errors!

**Comment by dan98765** [comment]
@coolboiime will do- I'll update here once the error format is changed. I'm aiming for today or tomorrow.

The new format will use the 'extensions' field described in the graphql spec. For example:
```
{
    "errors": [
        {
            "message": "The requested business could not be found.",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "extensions": {
                "code": "BUSINESS_NOT_FOUND"
            }
        }
    ],
    "data": {
        "business": null
    }
}
```
This way you can get the machine-friendly code by doing `response['errors']['extensions']['code']`. Note however that when this 1st goes out not every error will have a code (validation errors in particular aren't coded yet) but I hope to add codes to every error in the future, and certainly all will have codes before the graphql API is out of beta.

**Comment by coolboiime** [comment]
Got it! Thank you for the update

**Comment by dan98765** [comment]
This change is going out now; expect to see the new field on errors in the next 15-20 minutes. Please report any issues you encounter!

**Comment by dan98765** [comment]
Changelog entry: https://www.yelp.com/developers/graphql/changelog#changelog-20180705
