### ISSUE TITLE
Unable to retrieve search data using React Native

### ISSUE THREAD

**Issue by anmoldas** [Yelp/yelp-fusion#459]
I created an authentication token and tried adding it to the React Native framework, but no data is being pulled in. How exactly am I supposed to add the token to the GET request by using React Native/Javascript?

**Comment by teekwak** [comment]
Hi @anmoldas,

I believe you can use the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to make requests from React. You can add your API key in the request header there.

If you directly make requests from the frontend of your React Native app to the Yelp Fusion API, I believe you will run into a CORS issue. If that is the case, then you will need to make requests to Yelp Fusion API from your backend.

**Comment by Alberto-Funk** [comment]
Hello @teekwak ,

Can you expand on handling the CORS issue. I am sure this is due to my lack of knowledge.
I have tried making REST and GraphQL requests directly from front end, which result in the CORS issue.
Does this mean that when it comes to requests, you can only make requests via the server?

If so, how would that work?
I got it working by using axios on the back end, and another axios on the front end, but I feel like that is not a good solution.
Similar with GraphQL, would I have to construct my own GraphQL on the back end to adhere to CORS? Or make a Apollo request via server(which does not make sense to me)?

I haven't been able to find any other workaround to the CORS issue.

So far these requests have been test request, so I have been using codesandbox and localhost

**Comment by Alberto-Funk** [comment]
Sorry to butt in by the way!!
