### ISSUE TITLE
Yelp Reviews only return 3 reviews

### ISSUE THREAD

**Issue by BoPengGit** [Yelp/yelp-fusion#466]
## Overview
- **Issue type:** (Question)
- **Summary:** When I use the yelp reviews endpoint, it only returns 3 reviews for each query. Can I get the full number of reviews for a business?

## Description
When I use the yelp reviews endpoint, it only returns 3 reviews for each query. Can I get the full number of reviews for a business?

### Endpoint
Reviews

### Parameters or Sample Request
yelp_api.reviews_query(id='amys-ice-creams-austin-3')

### Response
{'reviews': [{'id': 'OOqgYLORqzDAdq1g27CBgw',
   'text': 'Checked this place out on a whim on my birthday during a sudden desire for the creamed ice and these guys were phenomenal, and my ice cream was even better....',
   'rating': 5,
   'time_created': '2018-03-10 15:53:11',
   'user': {'id': '-HhFi6o9tS5qCegfItHNPA',
    'profile_url': 'https://www.yelp.com/user_details?userid=-HhFi6o9tS5qCegfItHNPA',
    'image_url': 'https://s3-media2.fl.yelpcdn.com/photo/nq-zFi8ExaqFlARtK3O6MQ/o.jpg',
    'name': 'James L.'}},
  {'id': 'TwYoCb_TjlmLVLLvBFOoBg',
   'text': 'The ice cream was good, the aloha was my favorite.  \nIt was our first time there and it was about 1 hr and 15 min until closing time. We walk in and the...',
   'rating': 2,
   'time_created': '2018-08-15 15:48:40',
   'user': {'id': 'EU_AziWbt2VWktNuTHhJag',
    'profile_url': 'https://www.yelp.com/user_details?userid=EU_AziWbt2VWktNuTHhJag',
    'image_url': 'https://s3-media3.fl.yelpcdn.com/photo/-eh_qUKrc_sp-PFz22Mkcg/o.jpg',
    'name': 'Julien Y.'}},
  {'id': 'YngScPjiSfDCd0JWMheaBQ',
   'text': 'After checking out the Hope Outdoor Gallery nearby, my cousins, dude and I got some ice cream. If I were to describe this place, it is like a weird,...',
   'rating': 4,
   'time_created': '2018-08-04 13:17:50',
   'user': {'id': 'hYWwocw-J4KdyGLrUlOYXA',
    'profile_url': 'https://www.yelp.com/user_details?userid=hYWwocw-J4KdyGLrUlOYXA',
    'image_url': 'https://s3-media4.fl.yelpcdn.com/photo/pbDkQq1IQRoCRrVG_QSXsw/o.jpg',
    'name': 'Felicia L.'}}],
 'total': 345,
 'possible_languages': ['en']}

**Comment by shenyi1028** [comment]
As [https://www.yelp.com/developers/documentation/v3](https://www.yelp.com/developers/documentation/v3) saying "Return up to 3 review excerpts for a business.", I think 3 is the maximum.

**Comment by richierocks** [comment]
I checked some old review queries I'd stored from October 2017, and it seems that the limit of 3 review responses was also in place back then.

That said, it's pretty annoying. A limit of 3 reviews makes it impossible to do much text analysis. I'd love to be able to do sentiment analysis or topic modeling of reviews.

My suggestion for the V4 API would be to add `limit` and `offset` arguments (so it works the same as business search), perhaps keeping the default limit to 3 for backwards compatibility.

**Comment by dan98765** [comment]
Hi @BoPengGit, as @shenyi1028 correctly pointed out, the [Business Reviews Endpoint docs](https://www.yelp.com/developers/documentation/v3/business_reviews) specify that only three reviews are returned. 

Since folks might land on this issue due to google searching, I'll drop some info below that is not all relevant to your particular case. 

- Yelp's reviews are one of its most valuable assets, so we strike a careful balance when making some of them available publicly via the API. We chose to expose more reviews in the v3 API than we had in the v2 API, and continue to revisit this topic internally on a regular basis.
- If you are looking for more reviews to build a cool consumer-facing app of some kind, you can try applying for [Yelp Fusion VIP](https://www.yelp.com/fusion/vip) and pitch us your product.
- If you are looking for more reviews to do text analysis on for an academic project, please check out the [Yelp Academic Dataset](https://www.yelp.com/dataset) which contains a huge dump of reviews.

Also, this probably comes as no surprise, but scraping yelp.com for data is against Yelp's ToS.

**Comment by BoPengGit** [comment]
hi @dan98765 , do you know what is the cost for Yelp Fusion VIP?

Thanks for the help!

**Comment by GolangGuy** [comment]
[buy fake yelp reviews](http://freepage.io)
