### ISSUE TITLE
business details endpoint failing

### ISSUE THREAD

**Issue by Gabe-SpotMe** [Yelp/yelp-fusion#496]
## Overview
- **Issue type:** bug
- **Summary:** We're trying to pull business details but the endpoint is occasionally failing.  The majority of calls work like they are supposed to but some result in a 403 error.
- **Platform:** We're using [Yelp PHP Client](https://github.com/stevenmaguire/yelp-php) but it appears to be unrelated to the library.  This error is coming from the Yelp webservice.

## Description
Certain API calls to the business details endpoint result in a 403 response with this message:
```{"error": {"code": "BUSINESS_UNAVAILABLE", "description": "We may not be able to provide details for certain businesses, (truncated...)```

## More information
Not sure if it's relavent, but the search endpoint doesn't reveal these businesses either.  These aliases, however, are all visible on yelp.com.

### Endpoint
Here are a few examples of calls that have this result:
- https://api.yelp.com/v3/businesses/powerhouse-gym-and-rockells-family-fitness-center-rochester
- https://api.yelp.com/v3/businesses/princeton-health-and-fitness-center-princeton
- https://api.yelp.com/v3/businesses/curves-for-women-w-chester-east-west-chester

**Comment by dan98765** [comment]
Hi @Gabe-SpotMe thanks for filling out the issue template and giving examples. With the examples you provided it looks like this is the expected behavior. Those businesses do not have reviews so are not accessible via the API. Please see the [FAQ](https://www.yelp.com/developers/faq) question "Why does the API not return some businesses that I can find on Yelp?".
