### ISSUE TITLE
VIP Upgrade

### ISSUE THREAD

**Issue by Hsanka6** [Yelp/yelp-fusion#497]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(eg. feature request, bug, question, etc)_
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description
I requested vip upgrade to access the more business attributes more than a month ago and I still haven't gotten accepted

## More information
I want to make an app where users can pick what type of setting they want for food. For example date, instagram worthy/trendy, late night. Is there any other way I can get a specific cuisine and this setting 

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by dan98765** [comment]
Due to the volume of VIP requests, our Fusion VIP team is unable to respond to every request. VIP access is granted to those who meet our selection criteria. Being an independent developer does not mean you will never get VIP access - it depends on the product you build and how well it performs. That said, please check in with us again once your product is launched and gains substantial user traffic - we'll be glad to reevaluate your request then.
