### ISSUE TITLE
booking endpoint "Resource could not be found." error

### ISSUE THREAD

**Issue by PenguenUmut** [Yelp/yelp-fusion#529]
## Overview
- **Client ID:** 68dQB46B8HiE-cyWE0sarw
- **Issue type:** bug
- **Summary:** booking/ endpoint return "Resource could not be found."
- **Platform:** web

## Description

Hello,

I have an API Key and follow this api documentation;

https://www.yelp.com/developers/documentation/v3/

There are 3 endpoints under the Endpoint Documentation;
	* Business Endpoints (I got success responses from all path in this endpoint)
	* Event Endpoints (I am not interested with it)
	* Category Endpoints (I do not have access because I am not a beta user. I am not interested)

I tried booking reservation for a business but I couldn't find any endpoint on this documantation.

I searched a reservation endpoint and found this api doc url for booking;
	https://docs.developer.yelp.com/docs/endpoints-4#section-openings-endpoint 
and tried booking endpoint with my same api key but I got "Resource could not be found" error.

### Sample Request

```
curl -X GET 'https://api.yelp.com/v3/bookings/kinka-izakaya-original-toronto/openings?covers=2&date=2019-08-21&time=11:00' \
	 -H 'Authorization: Bearer {my_same_api_key}'
```

### Response
```
{
 "error":
  {
   "code": "NOT_FOUND",
   "description": "Resource could not be found."
  }
} 
```

## Extra question
What is the difference between these two documentation?
Why do both documentations have extra endpoints?

https://www.yelp.com/developers/documentation/v3/
doesn't have "booking/" endpoint

https://docs.developer.yelp.com/docs/
doesn't have "autocomplete/" endpoint.

**Comment by yifanli78** [comment]
Hi @PenguenUmut Thank you for asking the question! Unfortunately, Booking API belongs to a set of private endpoints. The access to Booking API and other private endpoints is restricted to business partners with approval from Yelp.

To answer you second question, https://docs.developer.yelp.com/docs/ was created for business partners, while https://www.yelp.com/developers/documentation/v3/ was created for general public API users, which is why you could not find booking API in the latter one. Hope this helps!

**Comment by AnithaNarayanasamy** [comment]
Hi @yifanli78 
Can you please let us the procedure to get access for Booking APIs. 
Thanks in Advance.
