### ISSUE TITLE
Business search crashes when location string too long

### ISSUE THREAD

**Issue by nicedawg** [Yelp/yelp-fusion#54]
This search works: 

`https://api.yelp.com/v3/businesses/search?term=Some+really+great+food+to+consume&location=the+city+600+miles+from+h&categories=restaurants%2Cbars`

but if I add one more character to the location string, I get a 500 error: 

`https://api.yelp.com/v3/businesses/search?term=Some+really+great+food+to+consume&location=the+city+600+miles+from+he&categories=restaurants%2Cbars`

Are there undocumented character limits? (Or maybe they're documented and I didn't notice?)

**Comment by tomelm** [comment]
What are the actual queries you're sending? That'll help us debug

**Comment by mittonk** [comment]
Reproduced error, using searches detailed above.  

500 is definitely a bug --- I could imagine a 4xx with a detailed error message if we're hitting a `location` length limit, but this is just plain crashing.

**Comment by mittonk** [comment]
Tripping over some very similar back-end errors in #69 .  

I think the length is mostly a red herring, and the issue is actually that we 500 if we don't recognize the search location.

Looks like "the+city+600+miles+from+h" is returning locations around London postal code "W1U 1HE".

Looks like "the+city+600+miles+from+he" is failing to find a location, and 500ing as a result.

So, this might actually be a dup of #69.

**Comment by mittonk** [comment]
Now giving a more helpful error message:
* https://api.yelp.com/v3/businesses/search?term=food&location=the+city+600+miles+from+he
```
{
  "error": {
    "code": "VALIDATION_ERROR",
    "description": {
      "error": {
        "code": "LOCATION_NOT_FOUND",
        "description": "Could not execute search, try specifying a more exact location."
      }
    }
  }
}
```

Long strings still work, if we can find a location based on them (please don't imitate this way of describing a location):
* https://api.yelp.com/v3/businesses/search?term=burgers&location=on+the+sidewalk+near+the+street+somewhere+in+denver
