### ISSUE TITLE
African American Owned Businesses API Call

### ISSUE THREAD

**Issue by stephenandersondev** [Yelp/yelp-fusion#596]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** API Call
- **Summary:** API Call on African American Owned Businesses
- **Platform:** Web

## Description
I don't see anywhere in the API docs where we can call on African American owned businesses, but you can search them through Yelp. Is this available?

https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information

**Comment by kvn219** [comment]
Do we have an update on this? I'd like to search up black-owned businesses.

**Comment by stong1108** [comment]
I believe you need Yelp Fusion VIP (instead of regular Yelp Fusion) to get business attributes according to this page: https://www.yelp.com/developers/documentation/v3/business

I'm trying to do something similar and am wondering how long it takes for VIP API access to be approved / rejected: https://github.com/Yelp/yelp-fusion/issues/603
