### ISSUE TITLE
Yelp Fusion Business Reviews - Analytics

### ISSUE THREAD

**Issue by oporter1** [Yelp/yelp-fusion#639]
## Overview
- **Client ID:** _Ny1Zhjpm6lDAhpuQL0C9Q
- **Issue type:** question
- **Summary:** I understand that there is a limit to 3 reviews for the Yelp Fusion Business API for reviews. I want to bring all of the reviews for a single company so their analytics team can create some reports. Is there a way around the 3 reviews if it is just for analytics? Is it possible to purchase more than the 3?

- **Platform:** Desktop/web

## Description
I understand that there is a limit to 3 reviews for the Yelp Fusion Business API for reviews. I want to bring all of the reviews for a single company so their analytics team can create some reports. Is there a way around the 3 reviews if it is just for analytics? Is it possible to purchase more than the 3?

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
https://api.yelp.com/v3/businesses/{businessName}/reviews

**Comment by anthonyangel1982** [comment]
Hi Olivia. If the Yelp Fusion Business API will not collect all of the reviews, have you considered making a web scraper to do it manually? An HTTP request will pull all of the yelp reviews, as your browser does, and then you could make a parser that weeds out all of the text of the reviews.

**Comment by anthonyangel1982** [comment]
I remembered your post when I ran across some repos on Github while trying to do my own Yelp scraping. See below. You may have to modify the Python scripts slightly if Yelp changed the format of their website since these repos were last updated. There seem to be other such repos on Github, possibly more recent, I didn't look at all of them.

https://github.com/thomkitchen/yelp-review-scraper  ("Web scraper that grabs all reviews for a business's yelp page and returns them as a string for parsing.")

https://github.com/m-millions/yelp-reviews-scraper  (This one does use Yelp Fusion Business API)

**Comment by oporter1** [comment]
thank you @anthonyangel1982 I will check it out and get back to you if it works. For now it seems like web scraping is the only way to go about this.
