### ISSUE TITLE
API v3 SSL connection errors

### ISSUE THREAD

**Issue by Sp23-23** [Yelp/yelp-fusion#693]
## Overview
- **Client ID:** NcTwtdNyNKXdcZCeq2-__w
- **Issue type:** SSL connection errors
- **Summary:** a call to "https://api.yelp.com/v3/businesses/search/phone" endpoint generated errors
- **Platform:** Microsoft Windows Server 2012 R2

## Description
System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.

## More information
My server is a Microsoft Windows Server 2012 R2 and it is configured to use a TLS 1.2 protocol as it is the highest supported TLS version. Your server seems to be using the newest TLS 1.3 protocol which is not supported by my server. 

### Endpoint
https://api.yelp.com/v3/businesses/search/phone

## Extra information
Could you please take a look at this issue and let me know how I can fix this?

**Comment by bizmate** [comment]
It looks like you know what to do but you dont want to? 
You wrote 
`Your server seems to be using the newest TLS 1.3 protocol which is not supported by my server
`
You should have posted it on StackOverflow because this is not a bug on Yelp but you are using an outdated setup.
https://www.appviewx.com/blogs/why-is-tls-1-3-better-and-safer-than-tls-1-2/#:~:text=While%20TLS%201.2%20can%20still,vulnerabilities%2C%20and%20also%20improves%20performance.

**Comment by Sp23-23** [comment]
Hi Diego,

Thank you for your reply.

Is it possible to add supporting TLS 1.2 in addition to the TLS 1.3 on your
side?

Thank you very much for your time and consideration.

Best regards,
Alex Crystal

**Comment by bizmate** [comment]
hi Alex, I am not from Yelp. And no it is an outdated technology. You need to fix your server as it is too out of date and insecure

**Comment by rockdog** [comment]
Hi @Sp23-23, we have deprecated using TLS 1.2 and hence won't add support for it back again.
