### ISSUE TITLE
Clarify client_id == App ID in docs.

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-fusion#71]
- https://www.yelp.com/developers/documentation/v3/get_started

@chribsen writes:

> The documentation seems to use different words for the same things. I'm guessing that `client_id` and `App ID` refers to the same thing.

People shouldn't be guessing, let's clarify this.

**Comment by dan98765** [comment]
Since this ticket was filed, we've split the [authentication guide](https://www.yelp.com/developers/documentation/v3/authentication) off from [get started](https://www.yelp.com/developers/documentation/v3/get_started). The get started page does not directly mention api keys or client ID anymore. We are also now using API Keys instead of oauth2 tokens for auth. 

Closing out this issue.
