### ISSUE TITLE
HTTP Status 500 and 429

### ISSUE THREAD

**Issue by cambuilt** [Yelp/yelp-fusion#77]
It appears that I have reached my call limit which I determined due to getting errors 500 and 429 (Too many requests) I contacted api@yelp.com and was granted an increase to 50,000 calls per day. However, I am still getting error 500. 

First, I make this call to authenticate:

https://api.yelp.com/oauth2/token?grant_type=client_credentials&client_id=[clientid]&client_secret=[secret] 

That gives me a successful code 200, but this returns a 500 (Unknown error):

https://api.yelp.com/v3/businesses/search?categories=restaurant&latitude=38.9890678045225&longitude=-77.0978405174881&radius=10000&offset=0

**Comment by mittonk** [comment]
@cambuilt : Ah, found a misconfiguration in your access limit.  Try again now?

**Comment by bizmate** [comment]
Sorry to hijack the conversation but how can these issues be avoided ahead? i.e. 

1. is there a way to know the usage of the API without tracking this on the client side (i.e. analytics on the api management page?)
2. is anything in the api going to send a usage notification based on a threshold? (btw I noticed i can contact api@yelp to request additional if required)

**Comment by mittonk** [comment]
@bizmate : Both definitely good ideas for the future --- neither's in place yet.

**Comment by cambuilt** [comment]
Thanks, mittonk, but still getting HTTP status 500 with the same search.

**Comment by mittonk** [comment]
@cambuilt : OK, I can repro that 500 on my own key --- so it's unrelated to your daily request limit.

Changing `categories=restaurant` to `categories=restaurants` gives a 200 and reasonable-looking results like https://www.yelp.com/biz/suma-bethesda-2

So,
For you: Check the category list at
* https://www.yelp.com/developers/documentation/v3/all_category_list

For Yelp: this should give a helpful `NO_SUCH_CATEGORY` error instead of an unhelpful 500.

**Comment by cambuilt** [comment]
Thanks Ken, that fixed my issue!

**Comment by mittonk** [comment]
That busted categories query now returns:
```
{
  "error": {
    "code": "INVALID_CATEGORY",
    "description": "The category alias you specified is not valid"
  }
}
```
