### ISSUE TITLE
Access Token Expiration

### ISSUE THREAD

**Issue by clamey** [Yelp/yelp-fusion#84]
It looks like for a given client_id/client_secret we are returned a single access_token that expires in 180 days after the first time it's requested.  Subsequent calls with the same client_id/client_secret returns the same access_token with the expires_in decrementing down.

How do we generate a new/different token so that first one doesn't expire on us?

**Comment by mittonk** [comment]
Reproduced behavior, digging in a little.

**Comment by mittonk** [comment]
OK, there's a few moving parts here.

The expected flow is:
1. You only get one token at a time.
2. You should build retrying into their request; if your request fails with an expired token, you should get a fresh one and try again.

However, #78 shows that instead of a nice HTTP 401 INVALID_TOKEN response in that case, we're giving a 500 --- and trying to refresh your tokens based on a 500 seems like overkill.

So, this is an issue.

Next steps:
1. Definitely: Fix #78 and give a proper error message on expired tokens.
2. Definitely: Explain the expectations in the docs.
3. Maybe: Reconsider possible flows to get multiple tokens --- but I don't think that would actually improve the situation much.

@clamey : Does that make some sense?  How does that sound for a workflow?

**Comment by clamey** [comment]
We can change to handle that.  FYI that I can't think of another API that does it that way, most have a way to renew the token's end date without waiting for it to error.  Also have to think about how best to test the expiration.

**Comment by mittonk** [comment]
(We should also clarify the docs in #98 .)

**Comment by mittonk** [comment]
#78 fixed, now we get a much clearer 401.

**Comment by swiftSlinger** [comment]
Hey!  Was just wondering, do you guys know if there are any updates to this?  I'd like to go ahead with the Yelp API, but not keen on having to manually re-new the access token every 180 days!

**Comment by tomelm** [comment]
@Super-Amazing-Joey-Boy we updated expiration dates on access tokens to be much longer lived so you shouldn't need to worry about that anymore (they're set to expire in 2038), see the [changelog](https://www.yelp.com/developers/v3/changelog#changelog-20170908). We're working to transition to completely non-expiring api keys in the next few months and we'll be sending out more information about that in the future. Anything you use the token for now will still work in the future so you shouldn't need to worry about any issues!
