### ISSUE TITLE
Sample code for yelp fusion

### ISSUE THREAD

**Issue by shuaiqih** [Yelp/yelp-fusion#96]
Although there are awesome sample code for v2, there seems to be no sample code for yelp fusion? Without the sample code it it quite hard for beginners to get started...Can anyone give some sample code about authentication and how to search the result?

**Comment by bizmate** [comment]
V2 had a certain level of complexity due to over engineered authentication. V3 is very simple and the full logic is visible through the documentation starting from Get started - https://www.yelp.com/developers/documentation/v3/get_started

The Http calls are so simple in general and well documented that providing and maintaining sample code is too much of an overhead for it.

If you use PHP go and you do not know how to perform an HTTP call check out Guzzle and use it to call the V3 api.
http://docs.guzzlephp.org/en/latest/

**Comment by mittonk** [comment]
Yes, I'd love to publish some example code in several languages.  We're looking into it!

**Comment by tonybadguy** [comment]
@mittonk Some projects maintain a page with links to external libraries of various languages. I think I've seen a couple of libs for this api so that might be helpful. I've also written one for node.js with sample code if anyone's interested: https://github.com/tonybadguy/yelp-fusion. Swagger's the way to go though.

**Comment by mittonk** [comment]
Started with a few!
* https://github.com/Yelp/yelp-fusion#clientlibs
* https://github.com/Yelp/yelp-fusion#code-samples

**Comment by mittonk** [comment]
That brings us up to Python, Ruby, and Node examples --- thanks @tonybadguy !
